### ISSUE TITLE
Upgrade to aws-sdk v3

### ISSUE THREAD

**Issue by yusufkandemir** [nestjs-packages/sqs#282]
This project is already using `sqs-consumer` v6 which uses `aws-sdk` v3 under the hood.
`sqs-producer` needs to be upgraded to v3: #273

Then, the `aws-sdk` itself in this project needs to be upgraded to v3, additional changes might or might not be needed.

**Comment by greatSumini** [comment]
@ybh1760 can you resolve this?

**Comment by Kraloz** [comment]
Are there any advances for this issue?

**Comment by sstopkin** [comment]
This issue is still important!
