### ISSUE TITLE
Get rid of AWS SDK 2.x.x

### ISSUE THREAD

**Issue by zoryamba** [nestjs-packages/sqs#433]
Hello.
First of. all, thanks to all maintainers and contributors for very useful library.

Found an issue in library dependencies. Library use AWS SDK 3 aside with AWS SDK 2. AWS is going to stop development of v2 version, which it notifies about, when I start my project:

```
(node:125) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

It's already been done in this MR: https://github.com/nestjs-packages/sqs/pull/404 but it somewhy was closed as wontfix. 

Could you please review this MR and merge it, or comment if something wrong here.

Thank you.

**Comment by zoryamba** [comment]
Attached new MR. Could you review it please? 
https://github.com/nestjs-packages/sqs/pull/434

**Comment by zoryamba** [comment]
Any chance this will be merged? Is lib still maintained by anyone??

**Comment by zoryamba** [comment]
up

**Comment by ruscon** [comment]
@zoryamba check this https://github.com/ssut/nestjs-sqs
